### ISSUE TITLE
依存ライブラリ設定追加

### ISSUE THREAD

**Issue by uchicom** [uchicom/spark#1]
# GOAL
depeandabot追加

# DESIGN
```
version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - uchicom
    labels:
      - "dependencies version up"
```
